classe tempo e treino do dia
bugs a se resolver: Aluno.java:3: error: duplicate class: Aluno
public class Aluno {
       ^
Main.java:143: error: alunos has private access in PersonalTrainer
                    Aluno alunoParaAvaliar = personalTrainer.alunos.get(indiceAdicionarAvaliacao - 1);
                                                            ^
Main.java:151: error: alunos has private access in PersonalTrainer
                    Aluno alunoParaRemoverAvaliacao = personalTrainer.alunos.get(indiceRemoverAvaliacao - 1);
                                                                     ^
Main.java:157: error: alunos has private access in PersonalTrainer
                    Aluno alunoParaVisualizarAvaliacoes = personalTrainer.alunos.get(indiceVisualizarAvaliacoes - 1);
                                                                         ^
Main.java:171: error: alunos has private access in PersonalTrainer
                    Aluno alunoParaEditarAvaliacao = personalTrainer.alunos.get(indiceEditarAvaliacao - 1);
                                                                    ^
Main.java:177: error: alunos has private access in PersonalTrainer
                    Aluno alunoParaGerarTreino = personalTrainer.alunos.get(indiceGerarTreino - 1);
                                                                ^
AlunoIdoso.java:9: error: constructor Aluno in class Aluno cannot be applied to given types;
    public AlunoIdoso(int pas, int pad, int bpm, int glicemia, String observacoes) {
                                                                                   ^
  required: String
  found: no arguments
  reason: actual and formal argument lists differ in length
Atleta.java:7: error: constructor Aluno in class Aluno cannot be applied to given types;
    public Atleta(boolean offseason, boolean precontest, int gramasCarb, int litrosAgua) {
                                                                                         ^
  required: String
  found: no arguments
  reason: actual and formal argument lists differ in length